### ISSUE TITLE
Ring of regeneration effect too short to apply health increase

### ISSUE THREAD

**Issue by RetroRodent** [machinespray/ROYAL#2]
The ring of regeneration applies Regen for 0 seconds but the effect has to be active for about 2 to 3 seconds before it increases the player's health by 1 point. (tested using a Psi spell with a duration of 1: no health was regained, this seems to be a vanilla limitation)

Minor note, regeneration is misspelled "regenaration" in RingActions.java

**Comment by machinespray** [comment]
Fixed in update 0.22(Will be on CurseForge soon)
