### ISSUE TITLE
Player dropped scroll upon death (rare)

### ISSUE THREAD

**Issue by RetroRodent** [machinespray/ROYAL#3]
Noticed an extra scroll in my loot after a corpse-run in singleplayer survival mode.

Tested by killing self repeatedly at the spawn point with /kill and an empty inventory. After about 32 deaths, a scroll of summon monster was picked up.

**Comment by machinespray** [comment]
Fixed in update 0.22(Will be on CurseForge soon).
Thank you for the help!
